[package]
name = "discord-rp"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-rpc-client = "0.4.0"
dotenvy = "0.15.7"
reqwest = {version = "0.12.24", features = ["json"]}
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }
zbus = "5.12.0"
zvariant = "5.8.0"
